patterns:
  about:
    title: "About Me"
    description: |
      This card will appear at the bottom of the home page. On wider screen sizes, the image and the text will be next to eachother. On smaller screen sizes, the image will be stacked ontop of the text.
  slider:
    title: "Other Videos"
    description: |
      This will appear on the homepage to allow people to view other videos that I have created for my YouTube channel.
  artwork:
    title: "Other Artwork"
    description: |
      This will appear at the bottom of the "Motion" page to allow people to view other artwork. This includes paper, canvas, and computer graphic illustrations.
  case-study:
    title: "Case Study card"
    description: |
      This will be the default layout for all the case studies.
    fields:
      - name: heading
        type: string
        example: "Travel Bohol"
      - name: about
        type: string
        example: "This video primarily focuses on a small island of Bohol, located in the Philippines. There is a steady tourism boost in Bohol, due to popular social media influencers who traveled there to seek adventure. However, there are not many promotional videos focusing on the chosen location."
      - name: inspiration
        type: string
        example: "This video primarily focuses on a small island of Bohol, located in the Philippines. There is a steady tourism boost in Bohol, due to popular social media influencers who traveled there to seek adventure. However, there are not many promotional videos focusing on the chosen location."
      - name: goals
        type: string
        example: "This video primarily focuses on a small island of Bohol, located in the Philippines. There is a steady tourism boost in Bohol, due to popular social media influencers who traveled there to seek adventure. However, there are not many promotional videos focusing on the chosen location."
      - name: thumbnail
        type: string
        example: "tourism.png"
      - name: video
        type: string
        example: "tourism.mp4"
      - name: image
        type: string
        example: "tourism.jpg"
      - name: plan
        type: string
        example: "This video primarily focuses on a small island of Bohol, located in the Philippines. There is a steady tourism boost in Bohol, due to popular social media influencers who traveled there to seek adventure. However, there are not many promotional videos focusing on the chosen location."
  motion-thumbnails:
    title: "Motion Thumbnails"
    description: |
      Thumbnails for all the motion graphics videos.
    fields:
      - name: data
        type: object
        data:
          source: "site.motion-arts[0]"
          type: Product
